-- GET THE COUNT(*)
-- CASE ODD, GET THE CEIL(N/2) TH ELEMENT BY LIMIT 1 OFFSET CEIL(N/2)
-- CASE EVEN, GET THE AVG OF N/2 AND N+2
-- ALL ROUND TO 4 
SET @TOTAL = (SELECT COUNT(*) FROM STATION);

SELECT ROUND(AVG(LAT_N), 4)
FROM 
    (SELECT LAT_N,
           ROW_NUMBER() OVER(ORDER BY LAT_N) AS NUM
    FROM STATION) SUB
WHERE (MOD(@TOTAL, 2) = 0 AND SUB.NUM IN (@TOTAL/2, (@TOTAL/2+1)))
OR    (SUB.NUM = (@TOTAL+1)/2)