SET @TOTAL = (SELECT COUNT(*) FROM STATION);

SELECT ROUND(AVG(LAT_N), 4)
FROM 
    (SELECT LAT_N,
           ROW_NUMBER() OVER(ORDER BY LAT_N) AS NUM
    FROM STATION) SUB
WHERE (MOD(@TOTAL, 2) = 0 AND SUB.NUM IN (@TOTAL/2, (@TOTAL/2+1)))
OR    (SUB.NUM = (@TOTAL+1)/2)