SELECT C.HACKER_ID, H.NAME, COUNT(C.HACKER_ID) AS C_COUNT
FROM HACKERS AS H
INNER JOIN CHALLENGES AS C
ON H.HACKER_ID = C.HACKER_ID
GROUP BY C.HACKER_ID, H.NAME
HAVING C_COUNT = 
-- MAX VALUE
(SELECT MAX(TEMP1.CNT) FROM(
SELECT COUNT(HACKER_ID) AS CNT FROM CHALLENGES GROUP BY
    HACKER_ID ORDER BY HACKER_ID
) AS TEMP1)
OR C_COUNT IN
(SELECT T.CNT FROM (SELECT COUNT(*) AS CNT 
                   FROM CHALLENGES
                   GROUP BY HACKER_ID) AS T
                    GROUP BY T.CNT
                    HAVING COUNT(T.CNT) = 1)
ORDER BY C_COUNT DESC, C.HACKER_ID;