/*
JOIN THE TABLE BY HACKER_ID -> TABLE SUBMISSION TOGETHER WITH HACKER ID'S NAME 

HACKER_ID NAME SUBMISSION_ID HACKER_ID CHALLENGE ID SCORE



FROM : 

GROUP BY HACKER_ID AND THEN GROUP BY THE CHALLENGE ID, 
AGGREGATE THE MAX SCORE FOR EACH CHALLENGE ID


THEN, GROUP BY HACKER_ID AND NAME, 
AGREGATE THE SUM OF SCORE (ALREADY THE MAXIMUM)
*/

SELECT H.HACKER_ID, H.NAME, SUM(MSCORE)
FROM 
HACKERS AS H INNER JOIN
(SELECT HACKER_ID, MAX(SCORE) AS MSCORE
FROM SUBMISSIONS 
GROUP BY CHALLENGE_ID, HACKER_ID) AS MAX_SCORE
ON H.HACKER_ID = MAX_SCORE.HACKER_ID
GROUP BY HACKER_ID, NAME
HAVING SUM(MSCORE) > 0
ORDER BY SUM(MSCORE) DESC, H.HACKER_ID;