SELECT NAME, GRADE, MARKS
FROM STUDENTS AS S, GRADES AS G
WHERE S.MARKS >= MIN_MARK AND S.MARKS <= MAX_MARK AND GRADE > 7
ORDER BY GRADE DESC, NAME ASC;

SELECT 'NULL', GRADE, MARKS
FROM STUDENTS AS S, GRADES AS G
WHERE S.MARKS >= MIN_MARK AND S.MARKS <= MAX_MARK AND GRADE <= 7
ORDER BY GRADE DESC, MARKS ASC;